services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: newtiger
      MYSQL_DATABASE: text2sql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - net

  user_interface:
    build:
      context: ./user_interface/
      dockerfile: ./Dockerfile
    container_name: user_interface
    restart: always
    ports:
      - 8600:8600
    depends_on:
      - backend
    volumes:
      - /app/text2sql/user_interface:/app/text2sql/user_interface
    networks:
      - net

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "update-ca-certificates && ollama serve & sleep 5 && ollama pull mistral && tail -f /dev/null"]
    networks:
      - net

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    image: backend
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - chroma
    volumes:
      - /app/text2sql/backend:/app/text2sql/backend
    networks:
      - net  

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
  ollama_models:

networks:
  net:
    driver: bridge